import Link from 'next/link';
import { Header } from '@/components/Header';
import { getDashboardData } from '@/lib/queries';
import { requireUser } from '@/lib/auth';

export const dynamic = 'force-dynamic';
export default async function AccountPage({ searchParams }: { searchParams: Promise<{ succes?: string }> }) {
  const user = await requireUser(); const { succes } = await searchParams; const data = await getDashboardData(user.id);
  return <><Header /><main className="container mx-auto px-4 py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-primary">MON ESPACE</p><h1 className="mt-2 text-4xl font-bold">Bonjour, {user.name}</h1><p className="mt-2 text-muted-foreground">{user.city} · {user.role === 'provider' ? 'Prestataire' : 'Client'}</p></div><Link href={user.role === 'provider' ? '/proposer' : '/publier'} className="rounded-md bg-primary px-5 py-3 font-bold text-primary-foreground">{user.role === 'provider' ? 'Modifier mon profil' : 'Nouvelle demande'}</Link></div>{succes && <p className="mt-6 rounded-md bg-secondary p-4 font-medium text-secondary-foreground">Vos informations ont bien ete enregistrees.</p>}<div className="mt-10 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-bold">Mes demandes</h2>{data.requests.length ? <div className="mt-4 divide-y">{data.requests.map((r: any) => <div key={r.id} className="py-4"><strong>{r.title}</strong><p className="mt-1 text-sm text-muted-foreground">{r.category} · {r.city} · {r.status === 'open' ? 'Ouverte' : 'Fermee'}</p></div>)}</div> : <p className="mt-4 text-muted-foreground">Vous n'avez encore publie aucune demande.</p>}</section><section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-bold">Mon profil professionnel</h2>{data.profile ? <div className="mt-4"><strong>{String(data.profile.headline)}</strong><p className="mt-2 text-sm text-muted-foreground">{String(data.profile.category)} · {data.profile.verified ? 'Profil verifie' : 'Verification a venir'}</p></div> : <p className="mt-4 text-muted-foreground">{user.role === 'provider' ? <Link className="font-bold text-primary" href="/proposer">Completer mon profil pour apparaitre dans l'annuaire</Link> : 'Creez un compte prestataire distinct pour proposer vos services.'}</p>}</section></div></main></>;
}
